version: '3.5'

services:
  ldap:
    image: osixia/openldap:latest
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=My Organization
      - LDAP_DOMAIN=my-domain.com
      - LDAP_BASE_DN=dc=my-domain,dc=com
      - LDAP_ADMIN_PASSWORD=adminpw
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=readonlypw
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
    command: "--copy-service"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./bootstrap/ldif:/container/service/slapd/assets/config/bootstrap/ldif
    ports:
      - "389:389"
      - "636:636"
    networks:
      - ldap_network

  lum:
    image: wheelybird/ldap-user-manager:v1.11
    restart: unless-stopped
    environment:
      - SERVER_HOSTNAME=lum.my-domain.com
      - LDAP_URI=ldap://ldap
      - LDAP_BASE_DN=dc=my-domain,dc=com
      - LDAP_REQUIRE_STARTTLS=false
      - LDAP_IGNORE_CERT_ERRORS=true
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=my-domain,dc=com
      - LDAP_ADMIN_BIND_PWD=adminpw
      - LDAP_USERS_DN=ou=people,dc=my-domain,dc=com
      - LDAP_GROUPS_DN=ou=groups,dc=my-domain,dc=com
      - USER_UID_START=10000
      - USER_GID_START=10000
      - EMAIL_DOMAIN=my-domain.com
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ldap
    networks:
      - ldap_network

networks:
  ldap_network:
    driver: bridge

volumes:
  ldap_data:
  ldap_config: